replicaCount: 1

image:
  repository: 992382687445.dkr.ecr.ap-southeast-1.amazonaws.com/nemibe
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  className: my-aws-ingress-class
  alb:
    name: ssl-ingress
    scheme: internet-facing
    certificateArn: arn:aws:acm:ap-southeast-1:992382687445:certificate/221e7931-4473-48b1-a566-d8a565a1f974
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  defaultBackend: false  # nếu muốn cấu hình default backend
