apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srs-nemi-tool.name" . }}
  labels:
    app: {{ include "srs-nemi-tool.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}   
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0   # ðŸ‘ˆ KhÃ´ng shutdown pod cÅ© Ä‘áº¿n khi pod má»›i ready
      maxSurge: 50%       # ðŸ‘ˆ Cho phÃ©p táº¡o thÃªm pod táº¡m thá»i
  selector:
    matchLabels:
      app: {{ include "srs-nemi-tool.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "srs-nemi-tool.name" . }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ include "srs-nemi-tool.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:   
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            initialDelaySeconds: 60  #  Chá» 10s sau khi container start
            periodSeconds: 5         #  Kiá»ƒm tra má»—i 5s
            failureThreshold: 3      #  Sau 3 láº§n fail => pod "not ready"
            successThreshold: 1      #  1 láº§n thÃ nh cÃ´ng => pod "ready"
          livenessProbe:
            initialDelaySeconds: 60  #  Chá» 10s sau khi container start
            periodSeconds: 5         #  Kiá»ƒm tra má»—i 5s
            failureThreshold: 3      #  Sau 3 láº§n fail => pod "not ready"
            successThreshold: 1      #  1 láº§n thÃ nh cÃ´ng => pod "ready"